"$schema" = 'https://starship.rs/config-schema.json'

#========================
# Prompt
#========================
add_newline = true
format = '''$directory$cmd_duration$git_branch$git_status$git_state$git_metrics
'''
right_format = "$env_var"

continuation_prompt = '❯ '

[character] # The name of the module we are configuring is 'character'
success_symbol = "[❯](bold green)"
error_symbol="[✗](bold red)"

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'

[git_branch]
symbol = "  "
style='bold purple'
format = '$symbol$branch(:$remote_branch)'
truncation_length = 30
truncation_symbol = '...'

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = "green bold"
modified = "*"

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = "cyan bold"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = ".../"

[env_var.MODE]
default = 'local'
format = "in [$env_value](white bold dimmed) "
